/*
 * Flexigrid for jQuery -  v1.1
 *
 * Copyright (c) 2008 Paulo P. Marinas (code.google.com/p/flexigrid/)
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 */
(function(a){a.addFlex=function(j,c){if(j.grid)return!1;c=a.extend({height:200,width:"auto",striped:!0,novstripe:!1,minwidth:30,minheight:80,resizable:!0,url:!1,method:"POST",dataType:"xml",errormsg:"Connection Error",usepager:!1,nowrap:!0,page:1,total:1,useRp:!0,rp:15,rpOptions:[10,15,20,30,50],title:!1,idProperty:"id",pagestat:"Displaying {from} to {to} of {total} items",pagetext:"Page",outof:"of",findtext:"Find",params:[],procmsg:"Processing, please wait ...",query:"",qtype:"",nomsg:"No items",
minColToggle:1,showToggleBtn:!0,hideOnSubmit:!0,autoload:!0,blockOpacity:0.5,preProcess:!1,addTitleToCell:!1,dblClickResize:!1,onDragCol:!1,onToggleCol:!1,onChangeSort:!1,onDoubleClick:!1,onSuccess:!1,onError:!1,onSubmit:!1},c);a(j).show().attr({cellPadding:0,cellSpacing:0,border:0}).removeAttr("width");var b={hset:{},rePosDrag:function(){a(b.cDrag).css({top:b.hDiv.offsetTop+1});a("div",b.cDrag).hide();a("thead tr:first th:visible",this.hDiv).each(function(){var d=a(this).outerWidth(!0),f=Math.floor(c.cgwidth/
2),d=0===k?Math.ceil(d-f):Math.ceil(a(this).position().left+d-f),f=a("thead tr:first th:visible",b.hDiv).index(this);isNaN(d)&&(d=0);a("div:eq("+f+")",b.cDrag).css({left:d+"px"}).show()})},fixHeight:function(d){var d=!1,d=a(b.bDiv).height(),f=a(this.hDiv).height();a("div",this.cDrag).each(function(){a(this).height(d+f)});parseInt(a(b.nDiv).height())>d?a(b.nDiv).height(d).width(200):a(b.nDiv).height("auto").width("auto");a(b.block).css({height:d,marginBottom:-1*d});var h=b.bDiv.offsetTop+d;"auto"!=
c.height&&c.resizable&&(h=b.vDiv.offsetTop);a(b.rDiv).css({height:h})},dragStart:function(d,f,h){if("colresize"==d){a(b.nDiv).hide();a(b.nBtn).hide();var d=a("div",this.cDrag).index(h),e=a("th:visible div:eq("+d+")",this.hDiv).width();a(h).addClass("dragging").siblings().hide();a(h).prev().addClass("dragging").show();this.colresize={startX:f.pageX,ol:parseInt(h.style.left),ow:e,n:d};a("body").css("cursor","col-resize")}else"vresize"==d?(d=!1,a("body").css("cursor","row-resize"),h&&(d=!0,a("body").css("cursor",
"col-resize")),this.vresize={h:c.height,sy:f.pageY,w:c.width,sx:f.pageX,hgo:d}):"colMove"==d&&(a(b.nDiv).hide(),a(b.nBtn).hide(),this.hset=a(this.hDiv).offset(),this.hset.right=this.hset.left+a("table",this.hDiv).width(),this.hset.bottom=this.hset.top+a("table",this.hDiv).height(),this.dcol=h,this.dcoln=a("th",this.hDiv).index(h),this.colCopy=document.createElement("div"),this.colCopy.className="colCopy",this.colCopy.innerHTML=h.innerHTML,a.browser.msie&&(this.colCopy.className="colCopy ie"),a(this.colCopy).css({position:"absolute",
"float":"left",display:"none",textAlign:h.align}),a("body").append(this.colCopy),a(this.cDrag).hide());a("body").noSelect()},dragMove:function(b){if(this.colresize){var f=this.colresize.n,h=b.pageX-this.colresize.startX,b=this.colresize.ol+h,h=this.colresize.ow+h;h>c.minwidth&&(a("div:eq("+f+")",this.cDrag).css("left",b),this.colresize.nw=h)}else if(this.vresize){if(f=this.vresize,h=b.pageY-f.sy,c.defwidth||(c.defwidth=c.width),"auto"!=c.width&&(!c.nohresize&&f.hgo)&&(b=f.w+(b.pageX-f.sx),b>c.defwidth&&
(this.gDiv.style.width=b+"px",c.width=b)),h=f.h+h,(h>c.minheight||c.height<c.minheight)&&!f.hgo)this.bDiv.style.height=h+"px",c.height=h,this.fixHeight(h)}else this.colCopy&&(a(this.dcol).addClass("thMove").removeClass("thOver"),b.pageX>this.hset.right||b.pageX<this.hset.left||b.pageY>this.hset.bottom||b.pageY<this.hset.top?a("body").css("cursor","move"):a("body").css("cursor","pointer"),a(this.colCopy).css({top:b.pageY+10,left:b.pageX+20,display:"block"}))},dragEnd:function(){if(this.colresize){var d=
this.colresize.n,f=this.colresize.nw;a("th:visible div:eq("+d+")",this.hDiv).css("width",f);a("tr",this.bDiv).each(function(){var c=a("td:visible div:eq("+d+")",this);c.css("width",f);b.addTitleToCell(c)});this.hDiv.scrollLeft=this.bDiv.scrollLeft;a("div:eq("+d+")",this.cDrag).siblings().show();a(".dragging",this.cDrag).removeClass("dragging");this.rePosDrag();this.fixHeight();this.colresize=!1;a.cookies&&a.cookie("flexiwidths/"+c.colModel[d].name,f)}else if(this.vresize)this.vresize=!1;else if(this.colCopy){a(this.colCopy).remove();
if(null!=this.dcolt&&(this.dcoln>this.dcolt?a("th:eq("+this.dcolt+")",this.hDiv).before(this.dcol):a("th:eq("+this.dcolt+")",this.hDiv).after(this.dcol),this.switchCol(this.dcoln,this.dcolt),a(this.cdropleft).remove(),a(this.cdropright).remove(),this.rePosDrag(),c.onDragCol))c.onDragCol(this.dcoln,this.dcolt);this.colCopy=this.dcolt=this.dcoln=this.hset=this.dcol=null;a(".thMove",this.hDiv).removeClass("thMove");a(this.cDrag).show()}a("body").css("cursor","default");a("body").noSelect(!1)},toggleCol:function(d,
f){var h=a("th[axis='col"+d+"']",this.hDiv)[0],e=a("thead th",b.hDiv).index(h),g=a("input[value="+d+"]",b.nDiv)[0];null==f&&(f=h.hidden);if(a("input:checked",b.nDiv).length<c.minColToggle&&!f)return!1;f?(h.hidden=!1,a(h).show(),g.checked=!0):(h.hidden=!0,a(h).hide(),g.checked=!1);a("tbody tr",j).each(function(){f?a("td:eq("+e+")",this).show():a("td:eq("+e+")",this).hide()});this.rePosDrag();if(c.onToggleCol)c.onToggleCol(d,f);return f},switchCol:function(b,c){a("tbody tr",j).each(function(){b>c?a("td:eq("+
c+")",this).before(a("td:eq("+b+")",this)):a("td:eq("+c+")",this).after(a("td:eq("+b+")",this))});b>c?a("tr:eq("+c+")",this.nDiv).before(a("tr:eq("+b+")",this.nDiv)):a("tr:eq("+c+")",this.nDiv).after(a("tr:eq("+b+")",this.nDiv));a.browser.msie&&7>a.browser.version&&(a("tr:eq("+c+") input",this.nDiv)[0].checked=!0);this.hDiv.scrollLeft=this.bDiv.scrollLeft},scroll:function(){this.hDiv.scrollLeft=this.bDiv.scrollLeft;this.rePosDrag()},addData:function(d){"json"==c.dataType&&(d=a.extend({rows:[],page:0,
total:0},d));c.preProcess&&(d=c.preProcess(d));a(".pReload",this.pDiv).removeClass("loading");this.loading=!1;if(!d){a(".pPageStat",this.pDiv).html(c.errormsg);if(c.onSuccess)c.onSuccess(this);return!1}c.total="xml"==c.dataType?+a("rows total",d).text():d.total;if(0==c.total){a("tr, a, td, div",j).unbind();a(j).empty();c.pages=1;c.page=1;this.buildpager();a(".pPageStat",this.pDiv).html(c.nomsg);if(c.onSuccess)c.onSuccess(this);return!1}c.pages=Math.ceil(c.total/c.rp);c.page="xml"==c.dataType?+a("rows page",
d).text():d.page;this.buildpager();var f=document.createElement("tbody");if("json"==c.dataType)a.each(d.rows,function(d,h){var e=document.createElement("tr");h.name&&(e.name=h.name);h.color?a(e).css("background",h.color):d%2&&c.striped&&(e.className="erow");h[c.idProperty]&&(e.id="row"+h[c.idProperty]);a("thead tr:first th",b.hDiv).each(function(){var b=document.createElement("td"),d=a(this).attr("axis").substr(3);b.align=this.align;b.innerHTML=typeof h.cell=="undefined"?h[c.colModel[d].name]:typeof h.cell[d]!=
"undefined"?h.cell[d]!=null?h.cell[d]:"":h.cell[c.colModel[d].name];d=b.innerHTML.indexOf("<BGCOLOR=");d>0&&a(b).css("background",text.substr(d+7,7));a(b).attr("abbr",a(this).attr("abbr"));a(e).append(b)});if(1>a("thead",this.gDiv).length)for(idx=0;idx<cell.length;idx++){var g=document.createElement("td");g.innerHTML="undefined"!=typeof h.cell[idx]?null!=h.cell[idx]?h.cell[idx]:"":h.cell[c.colModel[idx].name];a(e).append(g);g=null}a(f).append(e);e=null});else if("xml"==c.dataType){var h=1;a("rows row",
d).each(function(){h++;var d=document.createElement("tr");a(this).attr("name")&&(d.name=a(this).attr("name"));a(this).attr("color")?a(d).css("background",a(this).attr("id")):h%2&&c.striped&&(d.className="erow");var e=a(this).attr("id");e&&(d.id="row"+e);var e=null,g=this;a("thead tr:first th",b.hDiv).each(function(){var b=document.createElement("td"),c=a(this).attr("axis").substr(3);b.align=this.align;var c=a("cell:eq("+c+")",g).text(),f=c.indexOf("<BGCOLOR=");f>0&&a(b).css("background",c.substr(f+
7,7));b.innerHTML=c;a(b).attr("abbr",a(this).attr("abbr"));a(d).append(b)});1>a("thead",this.gDiv).length&&a("cell",this).each(function(){var b=document.createElement("td");b.innerHTML=a(this).text();a(d).append(b)});a(f).append(d);g=d=null})}a("tr",j).unbind();a(j).empty();a(j).append(f);this.addCellProp();this.addRowProp();this.rePosDrag();h=d=f=null;if(c.onSuccess)c.onSuccess(this);c.hideOnSubmit&&a(b.block).remove();this.hDiv.scrollLeft=this.bDiv.scrollLeft;a.browser.opera&&a(j).css("visibility",
"visible")},changeSort:function(d){if(this.loading)return!0;a(b.nDiv).hide();a(b.nBtn).hide();c.sortname==a(d).attr("abbr")&&(c.sortorder="asc"==c.sortorder?"desc":"asc");a(d).addClass("sorted").siblings().removeClass("sorted");a(".sdesc",this.hDiv).removeClass("sdesc");a(".sasc",this.hDiv).removeClass("sasc");a("div",d).addClass("s"+c.sortorder);c.sortname=a(d).attr("abbr");if(c.onChangeSort)c.onChangeSort(c.sortname,c.sortorder);else this.populate()},buildpager:function(){a(".pcontrol input",this.pDiv).val(c.page);
a(".pcontrol span",this.pDiv).html(c.pages);var b=(c.page-1)*c.rp+1,f=b+c.rp-1;c.total<f&&(f=c.total);var h=c.pagestat,h=h.replace(/{from}/,b),h=h.replace(/{to}/,f),h=h.replace(/{total}/,c.total);a(".pPageStat",this.pDiv).html(h)},populate:function(){if(this.loading)return!0;if(c.onSubmit&&!c.onSubmit())return!1;this.loading=!0;if(!c.url)return!1;a(".pPageStat",this.pDiv).html(c.procmsg);a(".pReload",this.pDiv).addClass("loading");a(b.block).css({top:b.bDiv.offsetTop});c.hideOnSubmit&&a(this.gDiv).prepend(b.block);
a.browser.opera&&a(j).css("visibility","hidden");c.newp||(c.newp=1);c.page>c.pages&&(c.page=c.pages);var d=[{name:"page",value:c.newp},{name:"rp",value:c.rp},{name:"sortname",value:c.sortname},{name:"sortorder",value:c.sortorder},{name:"query",value:c.query},{name:"qtype",value:c.qtype}];if(c.params.length)for(var f=0;f<c.params.length;f++)d[d.length]=c.params[f];a.ajax({type:c.method,url:c.url,data:d,dataType:c.dataType,success:function(a){b.addData(a)},error:function(a,b,d){try{if(c.onError)c.onError(a,
b,d)}catch(f){}}})},doSearch:function(){c.query=a("input[name=q]",b.sDiv).val();c.qtype=a("select[name=qtype]",b.sDiv).val();c.newp=1;this.populate()},changePage:function(b){if(this.loading)return!0;switch(b){case "first":c.newp=1;break;case "prev":1<c.page&&(c.newp=parseInt(c.page)-1);break;case "next":c.page<c.pages&&(c.newp=parseInt(c.page)+1);break;case "last":c.newp=c.pages;break;case "input":b=parseInt(a(".pcontrol input",this.pDiv).val()),isNaN(b)&&(b=1),1>b?b=1:b>c.pages&&(b=c.pages),a(".pcontrol input",
this.pDiv).val(b),c.newp=b}if(c.newp==c.page)return!1;if(c.onChangePage)c.onChangePage(c.newp);else this.populate()},addCellProp:function(){a("tbody tr td",b.bDiv).each(function(){var d=document.createElement("div"),f=a("td",a(this).parent()).index(this),f=a("th:eq("+f+")",b.hDiv).get(0);null!=f&&(c.sortname==a(f).attr("abbr")&&c.sortname&&(this.className="sorted"),a(d).css({textAlign:f.align,width:a("div:first",f)[0].style.width}),f.hidden&&a(this).css("display","none"));!1==c.nowrap&&a(d).css("white-space",
"normal");""==this.innerHTML&&(this.innerHTML="&nbsp;");d.innerHTML=this.innerHTML;var h=a(this).parent()[0],e=!1;h.id&&(e=h.id.substr(3));null!=f&&f.process&&f.process(d,e);a(this).empty().append(d).removeAttr("width");b.addTitleToCell(d)})},getCellDim:function(b){var c=parseInt(a(b).height()),e=parseInt(a(b).parent().height()),g=parseInt(b.style.width),j=parseInt(a(b).parent().width()),i=b.offsetParent.offsetTop,k=b.offsetParent.offsetLeft,l=parseInt(a(b).css("paddingLeft")),b=parseInt(a(b).css("paddingTop"));
return{ht:c,wt:g,top:i,left:k,pdl:l,pdt:b,pht:e,pwt:j}},addRowProp:function(){a("tbody tr",b.bDiv).on("click",function(d){var f=d.target||d.srcElement;if(f.href||f.type)return!0;!d.ctrlKey&&!d.metaKey&&(a(this).toggleClass("trSelected"),c.singleSelect&&!b.multisel&&a(this).siblings().removeClass("trSelected"))}).on("mousedown",function(c){c.shiftKey&&(a(this).toggleClass("trSelected"),b.multisel=!0,this.focus(),a(b.gDiv).noSelect());if(c.ctrlKey||c.metaKey)a(this).toggleClass("trSelected"),b.multisel=
!0,this.focus()}).on("mouseup",function(c){b.multisel&&(!c.ctrlKey&&!c.metaKey)&&(b.multisel=!1,a(b.gDiv).noSelect(!1))}).on("dblclick",function(){if(c.onDoubleClick)c.onDoubleClick(this,b,c)}).hover(function(c){b.multisel&&c.shiftKey&&a(this).toggleClass("trSelected")},function(){});a.browser.msie&&7>a.browser.version&&a(this).hover(function(){a(this).addClass("trOver")},function(){a(this).removeClass("trOver")})},combo_flag:!0,combo_resetIndex:function(a){this.combo_flag&&(a.selectedIndex=0);this.combo_flag=
!0},combo_doSelectAction:function(a){eval(a.options[a.selectedIndex].value);a.selectedIndex=0;this.combo_flag=!1},addTitleToCell:function(b){if(c.addTitleToCell){var f=a("<span />").css("display","none"),b=b instanceof jQuery?b:a(b),e=b.outerWidth(),g=0;a("body").children(":first").before(f);f.html(b.html());f.css("font-size",""+b.css("font-size"));f.css("padding-left",""+b.css("padding-left"));g=f.innerWidth();f.remove();g>e?b.attr("title",b.text()):b.removeAttr("title")}},autoResizeColumn:function(d){if(c.dblClickResize){var f=
a("div",this.cDrag).index(d),e=a("th:visible div:eq("+f+")",this.hDiv),d=parseInt(d.style.left),g=e.width(),j=0,i=a("<span />");a("body").children(":first").before(i);i.html(e.html());i.css("font-size",""+e.css("font-size"));i.css("padding-left",""+e.css("padding-left"));i.css("padding-right",""+e.css("padding-right"));j=i.width();a("tr",this.bDiv).each(function(){var b=a("td:visible div:eq("+f+")",this),c=0;i.html(b.html());i.css("font-size",""+b.css("font-size"));i.css("padding-left",""+b.css("padding-left"));
i.css("padding-right",""+b.css("padding-right"));c=i.width();j=c>j?c:j});i.remove();j=c.minWidth>j?c.minWidth:j;a("div:eq("+f+")",this.cDrag).css("left",d+(j-g));this.colresize={nw:j,n:f};b.dragEnd()}},pager:0};if(c.colModel){for(var n=document.createElement("thead"),e=document.createElement("tr"),k=0;k<c.colModel.length;k++){var g=c.colModel[k],i=document.createElement("th");a(i).attr("axis","col"+k);if(g){if(a.cookies){var l="flexiwidths/"+g.name;void 0!=a.cookie(l)&&(g.width=a.cookie(l))}void 0!=
g.display&&(i.innerHTML=g.display);g.name&&g.sortable&&a(i).attr("abbr",g.name);g.align&&(i.align=g.align);g.width&&a(i).attr("width",g.width);a(g).attr("hide")&&(i.hidden=!0);g.process&&(i.process=g.process)}else i.innerHTML="",a(i).attr("width",30);a(e).append(i)}a(n).append(e);a(j).prepend(n)}b.gDiv=document.createElement("div");b.mDiv=document.createElement("div");b.hDiv=document.createElement("div");b.bDiv=document.createElement("div");b.vDiv=document.createElement("div");b.rDiv=document.createElement("div");
b.cDrag=document.createElement("div");b.block=document.createElement("div");b.nDiv=document.createElement("div");b.nBtn=document.createElement("div");b.iDiv=document.createElement("div");b.tDiv=document.createElement("div");b.sDiv=document.createElement("div");b.pDiv=document.createElement("div");c.usepager||(b.pDiv.style.display="none");b.hTable=document.createElement("table");b.gDiv.className="flexigrid";"auto"!=c.width&&(b.gDiv.style.width=c.width+"px");a.browser.msie&&a(b.gDiv).addClass("ie");
c.novstripe&&a(b.gDiv).addClass("novstripe");a(j).before(b.gDiv);a(b.gDiv).append(j);if(c.buttons){b.tDiv.className="tDiv";i=document.createElement("div");i.className="tDiv2";for(k=0;k<c.buttons.length;k++)(e=c.buttons[k],e.separator)?a(i).append("<div class='btnseparator'></div>"):(g=document.createElement("div"),g.className="fbutton",g.innerHTML="<div><span>"+(e.hidename?"&nbsp;":e.name)+"</span></div>",e.bclass&&a("span",g).addClass(e.bclass).css({paddingLeft:20}),e.bimage&&a("span",g).css("background",
"url("+e.bimage+") no-repeat center left"),a("span",g).css("paddingLeft",20),e.tooltip&&(a("span",g)[0].title=e.tooltip),g.onpress=e.onpress,g.name=e.name,e.id&&(g.id=e.id),e.onpress&&a(g).click(function(){this.onpress(this.id||this.name,b.gDiv)}),a(i).append(g),a.browser.msie&&7>a.browser.version&&a(g).hover(function(){a(this).addClass("fbOver")},function(){a(this).removeClass("fbOver")}));a(b.tDiv).append(i);a(b.tDiv).append("<div style='clear:both'></div>");a(b.gDiv).prepend(b.tDiv)}b.hDiv.className=
"hDiv";if(c.combobuttons&&a(b.tDiv2)){g=document.createElement("div");g.className="fbutton";var m=document.createElement("select");a(m).change(function(){b.combo_doSelectAction(m)});a(m).click(function(){b.combo_resetIndex(m)});m.className="cselect";a(g).append(m);for(k=0;k<c.combobuttons.length;k++)if(e=c.combobuttons[k],!e.separator)i=document.createElement("option"),i.innerHTML=e.name,e.bclass&&a(i).addClass(e.bclass).css({paddingLeft:20}),e.bimage&&a(i).css("background","url("+e.bimage+") no-repeat center left"),
a(i).css("paddingLeft",20),e.tooltip&&(a(i)[0].title=e.tooltip),e.onpress&&(i.value=e.onpress),a(m).append(i);a(".tDiv2").append(g)}a(j).before(b.hDiv);b.hTable.cellPadding=0;b.hTable.cellSpacing=0;a(b.hDiv).append('<div class="hDivBox"></div>');a("div",b.hDiv).append(b.hTable);var n=a("thead:first",j).get(0);n&&a(b.hTable).append(n);n=null;if(!c.colmodel)var o=0;a("thead tr:first th",b.hDiv).each(function(){var d=document.createElement("div");if(a(this).attr("abbr")){a(this).click(function(c){if(!a(this).hasClass("thOver"))return false;
c=c.target||c.srcElement;if(c.href||c.type)return true;b.changeSort(this)});if(a(this).attr("abbr")==c.sortname){this.className="sorted";d.className="s"+c.sortorder}}this.hidden&&a(this).hide();c.colmodel||a(this).attr("axis","col"+o++);a(d).css({textAlign:this.align,width:this.width+"px"});d.innerHTML=this.innerHTML;a(this).empty().append(d).removeAttr("width").mousedown(function(a){b.dragStart("colMove",a,this)}).hover(function(){!b.colresize&&(!a(this).hasClass("thMove")&&!b.colCopy)&&a(this).addClass("thOver");
if(a(this).attr("abbr")!=c.sortname&&!b.colCopy&&!b.colresize&&a(this).attr("abbr"))a("div",this).addClass("s"+c.sortorder);else if(a(this).attr("abbr")==c.sortname&&!b.colCopy&&!b.colresize&&a(this).attr("abbr")){var d=c.sortorder=="asc"?"desc":"asc";a("div",this).removeClass("s"+c.sortorder).addClass("s"+d)}if(b.colCopy){d=a("th",b.hDiv).index(this);if(d==b.dcoln)return false;d<b.dcoln?a(this).append(b.cdropleft):a(this).append(b.cdropright);b.dcolt=d}else if(!b.colresize){var d=a("th:visible",
b.hDiv).index(this),d=parseInt(a("div:eq("+d+")",b.cDrag).css("left")),e=jQuery(b.nBtn).outerWidth(),e=d-e+Math.floor(c.cgwidth/2);a(b.nDiv).hide();a(b.nBtn).hide();a(b.nBtn).css({left:e,top:b.hDiv.offsetTop}).show();var g=parseInt(a(b.nDiv).width());a(b.nDiv).css({top:b.bDiv.offsetTop});e+g>a(b.gDiv).width()?a(b.nDiv).css("left",d-g+1):a(b.nDiv).css("left",e);a(this).hasClass("sorted")?a(b.nBtn).addClass("srtd"):a(b.nBtn).removeClass("srtd")}},function(){a(this).removeClass("thOver");if(a(this).attr("abbr")!=
c.sortname)a("div",this).removeClass("s"+c.sortorder);else if(a(this).attr("abbr")==c.sortname){var d=c.sortorder=="asc"?"desc":"asc";a("div",this).addClass("s"+c.sortorder).removeClass("s"+d)}if(b.colCopy){a(b.cdropleft).remove();a(b.cdropright).remove();b.dcolt=null}})});b.bDiv.className="bDiv";a(j).before(b.bDiv);a(b.bDiv).css({height:"auto"==c.height?"auto":c.height+"px"}).scroll(function(){b.scroll()}).append(j);"auto"==c.height&&a("table",b.bDiv).addClass("autoht");b.addCellProp();b.addRowProp();
e=a("thead tr:first th:first",b.hDiv).get(0);if(null!=e){b.cDrag.className="cDrag";b.cdpad=0;b.cdpad+=isNaN(parseInt(a("div",e).css("borderLeftWidth")))?0:parseInt(a("div",e).css("borderLeftWidth"));b.cdpad+=isNaN(parseInt(a("div",e).css("borderRightWidth")))?0:parseInt(a("div",e).css("borderRightWidth"));b.cdpad+=isNaN(parseInt(a("div",e).css("paddingLeft")))?0:parseInt(a("div",e).css("paddingLeft"));b.cdpad+=isNaN(parseInt(a("div",e).css("paddingRight")))?0:parseInt(a("div",e).css("paddingRight"));
b.cdpad+=isNaN(parseInt(a(e).css("borderLeftWidth")))?0:parseInt(a(e).css("borderLeftWidth"));b.cdpad+=isNaN(parseInt(a(e).css("borderRightWidth")))?0:parseInt(a(e).css("borderRightWidth"));b.cdpad+=isNaN(parseInt(a(e).css("paddingLeft")))?0:parseInt(a(e).css("paddingLeft"));b.cdpad+=isNaN(parseInt(a(e).css("paddingRight")))?0:parseInt(a(e).css("paddingRight"));a(b.bDiv).before(b.cDrag);var r=a(b.bDiv).height(),q=a(b.hDiv).height();a(b.cDrag).css({top:-q+"px"});a("thead tr:first th",b.hDiv).each(function(){var d=
document.createElement("div");a(b.cDrag).append(d);if(!c.cgwidth)c.cgwidth=a(d).width();a(d).css({height:r+q}).mousedown(function(a){b.dragStart("colresize",a,this)}).dblclick(function(){b.autoResizeColumn(this)});if(a.browser.msie&&a.browser.version<7){b.fixHeight(a(b.gDiv).height());a(d).hover(function(){b.fixHeight();a(this).addClass("dragging")},function(){b.colresize||a(this).removeClass("dragging")})}})}c.striped&&a("tbody tr:odd",b.bDiv).addClass("erow");c.resizable&&"auto"!=c.height&&(b.vDiv.className=
"vGrip",a(b.vDiv).mousedown(function(a){b.dragStart("vresize",a)}).html("<span></span>"),a(b.bDiv).after(b.vDiv));c.resizable&&("auto"!=c.width&&!c.nohresize)&&(b.rDiv.className="hGrip",a(b.rDiv).mousedown(function(a){b.dragStart("vresize",a,true)}).html("<span></span>").css("height",a(b.gDiv).height()),a.browser.msie&&7>a.browser.version&&a(b.rDiv).hover(function(){a(this).addClass("hgOver")},function(){a(this).removeClass("hgOver")}),a(b.gDiv).append(b.rDiv));if(c.usepager){b.pDiv.className="pDiv";
b.pDiv.innerHTML='<div class="pDiv2"></div>';a(b.bDiv).after(b.pDiv);e=' <div class="pGroup"> <div class="pFirst pButton"><span></span></div><div class="pPrev pButton"><span></span></div> </div> <div class="btnseparator"></div> <div class="pGroup"><span class="pcontrol">'+c.pagetext+' <input type="text" size="4" value="1" /> '+c.outof+' <span> 1 </span></span></div> <div class="btnseparator"></div> <div class="pGroup"> <div class="pNext pButton"><span></span></div><div class="pLast pButton"><span></span></div> </div> <div class="btnseparator"></div> <div class="pGroup"> <div class="pReload pButton"><span></span></div> </div> <div class="btnseparator"></div> <div class="pGroup"><span class="pPageStat"></span></div>';
a("div",b.pDiv).html(e);a(".pReload",b.pDiv).click(function(){b.populate()});a(".pFirst",b.pDiv).click(function(){b.changePage("first")});a(".pPrev",b.pDiv).click(function(){b.changePage("prev")});a(".pNext",b.pDiv).click(function(){b.changePage("next")});a(".pLast",b.pDiv).click(function(){b.changePage("last")});a(".pcontrol input",b.pDiv).keydown(function(a){a.keyCode==13&&b.changePage("input")});a.browser.msie&&7>a.browser.version&&a(".pButton",b.pDiv).hover(function(){a(this).addClass("pBtnOver")},
function(){a(this).removeClass("pBtnOver")});if(c.useRp){e=g="";for(i=0;i<c.rpOptions.length;i++)e=c.rp==c.rpOptions[i]?'selected="selected"':"",g+="<option value='"+c.rpOptions[i]+"' "+e+" >"+c.rpOptions[i]+"&nbsp;&nbsp;</option>";a(".pDiv2",b.pDiv).prepend("<div class='pGroup'><select name='rp'>"+g+"</select></div> <div class='btnseparator'></div>");a("select",b.pDiv).change(function(){if(c.onRpChange)c.onRpChange(+this.value);else{c.newp=1;c.rp=+this.value;b.populate()}})}if(c.searchitems){a(".pDiv2",
b.pDiv).prepend("<div class='pGroup'> <div class='pSearch pButton'><span></span></div> </div>  <div class='btnseparator'></div>");a(".pSearch",b.pDiv).click(function(){a(b.sDiv).slideToggle("fast",function(){a(".sDiv:visible input:first",b.gDiv).trigger("focus")})});b.sDiv.className="sDiv";g=c.searchitems;e=i="";for(l=0;l<g.length;l++)""==c.qtype&&!0==g[l].isdefault?(c.qtype=g[l].name,e='selected="selected"'):e="",i+="<option value='"+g[l].name+"' "+e+" >"+g[l].display+"&nbsp;&nbsp;</option>";""==
c.qtype&&(c.qtype=g[0].name);a(b.sDiv).append("<div class='sDiv2'>"+c.findtext+" <input type='text' value='"+c.query+"' size='30' name='q' class='qsbox' />  <select name='qtype'>"+i+"</select></div>");a("input[name=q]",b.sDiv).keydown(function(a){a.keyCode==13&&b.doSearch()});a("select[name=qtype]",b.sDiv).keydown(function(a){a.keyCode==13&&b.doSearch()});a("input[value=Clear]",b.sDiv).click(function(){a("input[name=q]",b.sDiv).val("");c.query="";b.doSearch()});a(b.bDiv).after(b.sDiv)}}a(b.pDiv,b.sDiv).append("<div style='clear:both'></div>");
c.title&&(b.mDiv.className="mDiv",b.mDiv.innerHTML='<div class="ftitle">'+c.title+"</div>",a(b.gDiv).prepend(b.mDiv),c.showTableToggleBtn&&(a(b.mDiv).append('<div class="ptogtitle" title="Minimize/Maximize Table"><span></span></div>'),a("div.ptogtitle",b.mDiv).click(function(){a(b.gDiv).toggleClass("hideBody");a(this).toggleClass("vsble")})));b.cdropleft=document.createElement("span");b.cdropleft.className="cdropleft";b.cdropright=document.createElement("span");b.cdropright.className="cdropright";
b.block.className="gBlock";e=a(b.bDiv).height();g=b.bDiv.offsetTop;a(b.block).css({width:b.bDiv.style.width,height:e,background:"white",position:"relative",marginBottom:-1*e,zIndex:1,top:g,left:"0px"});a(b.block).fadeTo(0,c.blockOpacity);if(a("th",b.hDiv).length){b.nDiv.className="nDiv";b.nDiv.innerHTML="<table cellpadding='0' cellspacing='0'><tbody></tbody></table>";a(b.nDiv).css({marginBottom:-1*e,display:"none",top:g}).noSelect();var p=0;a("th div",b.hDiv).each(function(){var c='checked="checked"';
a("th[axis='col"+p+"']",b.hDiv)[0].style.display=="none"&&(c="");a("tbody",b.nDiv).append('<tr><td class="ndcol1"><input type="checkbox" '+c+' class="togCol" value="'+p+'" /></td><td class="ndcol2">'+this.innerHTML+"</td></tr>");p++});a.browser.msie&&7>a.browser.version&&a("tr",b.nDiv).hover(function(){a(this).addClass("ndcolover")},function(){a(this).removeClass("ndcolover")});a("td.ndcol2",b.nDiv).click(function(){return a("input:checked",b.nDiv).length<=c.minColToggle&&a(this).prev().find("input")[0].checked?
false:b.toggleCol(a(this).prev().find("input").val())});a("input.togCol",b.nDiv).click(function(){if(a("input:checked",b.nDiv).length<c.minColToggle&&this.checked==false)return false;a(this).parent().next().trigger("click")});a(b.gDiv).prepend(b.nDiv);a(b.nBtn).addClass("nBtn").html("<div></div>").attr("title","Hide/Show Columns").click(function(){a(b.nDiv).toggle();return true});c.showToggleBtn&&a(b.gDiv).prepend(b.nBtn)}a(b.iDiv).addClass("iDiv").css({display:"none"});a(b.bDiv).append(b.iDiv);a(b.bDiv).hover(function(){a(b.nDiv).hide();
a(b.nBtn).hide()},function(){if(b.multisel)b.multisel=false});a(b.gDiv).hover(function(){},function(){a(b.nDiv).hide();a(b.nBtn).hide()});a(document).mousemove(function(a){b.dragMove(a)}).mouseup(function(){b.dragEnd()}).hover(function(){},function(){b.dragEnd()});a.browser.msie&&7>a.browser.version&&(a(".hDiv,.bDiv,.mDiv,.pDiv,.vGrip,.tDiv, .sDiv",b.gDiv).css({width:"100%"}),a(b.gDiv).addClass("ie6"),"auto"!=c.width&&a(b.gDiv).addClass("ie6fullwidthbug"));b.rePosDrag();b.fixHeight();j.p=c;j.grid=
b;c.url&&c.autoload&&b.populate();return j};var o=!1;a(document).ready(function(){o=!0});a.fn.flexigrid=function(j){return this.each(function(){if(o)a.addFlex(this,j);else{a(this).hide();var c=this;a(document).ready(function(){a.addFlex(c,j)})}})};a.fn.flexReload=function(){return this.each(function(){this.grid&&this.p.url&&this.grid.populate()})};a.fn.flexOptions=function(j){return this.each(function(){this.grid&&a.extend(this.p,j)})};a.fn.flexToggleCol=function(a,c){return this.each(function(){this.grid&&
this.grid.toggleCol(a,c)})};a.fn.flexAddData=function(a){return this.each(function(){this.grid&&this.grid.addData(a)})};a.fn.noSelect=function(j){return null==j||j?this.each(function(){a.browser.msie||a.browser.safari?a(this).bind("selectstart",function(){return!1}):a.browser.mozilla?(a(this).css("MozUserSelect","none"),a("body").trigger("focus")):a.browser.opera?a(this).bind("mousedown",function(){return!1}):a(this).attr("unselectable","on")}):this.each(function(){a.browser.msie||a.browser.safari?
a(this).unbind("selectstart"):a.browser.mozilla?a(this).css("MozUserSelect","inherit"):a.browser.opera?a(this).unbind("mousedown"):a(this).removeAttr("unselectable","on")})};a.fn.flexSearch=function(){return this.each(function(){this.grid&&this.p.searchitems&&this.grid.doSearch()})}})(jQuery);
